bugfix: config_check always return true

diff --git a/bin/kernelconfig b/bin/kernelconfig
--- a/bin/kernelconfig
+++ b/bin/kernelconfig
@@ -15,33 +15,34 @@ function config_check()
                 grep CONFIG_${CONFIG}=y .config >/dev/null || (
                     grep CONFIG_${CONFIG}= .config >&2;
                     echo ${CONFIG} should enabled >&2;
-                    return 6);
+                    return 1) || return $?;
             elif [ "a$m" == "a--module" ]; then
                 grep CONFIG_${CONFIG}=m .config >/dev/null || (
                     grep CONFIG_${CONFIG}= .config;
                     echo "${CONFIG} should be module)" >&2 ;
-                    return 2);
+                    return 1) || return $?;
             elif [ "a$m" == "a--set-val" ]; then
                 grep "CONFIG_${CONFIG}=$val" .config > /dev/null || (
                     grep CONFIG_${CONFIG}= .config;
                     echo "${CONFIG} should be $val" >&2;
-                    return 3);
+                    return 1) || return $?;
             elif [ "a$m" == "a--set-str" ]; then
                 grep "CONFIG_${CONFIG}=$val" .config > /dev/null || (
                     grep CONFIG_${CONFIG}= .config;
                     echo "${CONFIG} should be $val" >&2;
-                    return 4);
+                    return 1) || return $?;
             elif [ "a$m" == "a--disable" ]; then
                 grep CONFIG_${CONFIG}= .config > /dev/null && (
                     grep CONFIG_${CONFIG}= .config;
                     echo "${CONFIG} should disabled" >&2;
-                    return 5);
+                    return 1);
             fi
+            true  # overwrite return value generated by grep disabled module
         done
-        return 0
+        return $?
 }
 
-run()
+function run()
 {
     echo $@
     $@ || exit $?
